Repository allangrds/naming-cheatsheet, pull requests merged in 2022-10, with the labels that each got.

#10 chore: traduzir o tópico de naming convention
  README.md
Labels: documentation, good first issue, hacktoberfest

#11 feat: add translation for 's-i-d'
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#12 chore: translate avoid contractions
  README.md
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#13 feat: translate "avoid context duplication"
  README.md
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#14 feat: translate "reflect the expected result"
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#18 feat: translate "singular and plurals"
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022
